version: "3.3"
services:
  rest:
    container_name: similarity-api
    image: skinlyzer/similarity-api
    ports: 
      - "5000:5000"
    # environment:
    env_file: ".env"
    build:
      context: .
      